app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  stack-overflow-url:
    default-url: https://api.stackexchange.com/2.3/
  git-hub-url:
    default-url: https://api.github.com/
  telegram-bot-url:
    default-url: http://localhost:8090/bot/api/v1
spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  show-actuator: true
  swagger-ui:
    path: /scrapper/api/v1/swagger-ui
