app:
  telegram-token: ${TELEGRAM_API_KEY}
  scrapper-url:
    default-url: http://localhost:8080/scrapper/api/v1
  scrapper-retry-config:
    type: constant
    delay: 2s
    max-retries: 3
    retry-on-statuses:
      - SERVER_ERROR
  processed-link-updates-metric-name: processed_link_updates_total

kafka:
  topic-configurations:
    - name: linkUpdates
      partitions: 1
      replicas: 1

  consumer-configuration:
    bootstrap-servers: localhost:9092
    group-id: mainConsumerGroup
    auto-offset-reset: latest
    enable-auto-commit: true
    max-poll-interval: 10000
    concurrency: 3

  producer-configuration:
    bootstrap-servers: localhost:9092
    client-id: deadLetterProducerGroup
    acks-config: 1
    delivery-timeout: 100000
    linger-ms: 5000
    batch-size: 200000

  retryable-topic-attempts: 1
  dlt-topic-suffix: _dlt

management:
  metrics:
    tags:
      application: ${spring.application.name}

  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /
      path-mapping:
        prometheus : "metrics"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
    enabled-by-default: false
  server:
    port: 8091

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  docker:
    compose:
      enabled: true
      file: compose.yml

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  show-actuator: false
  swagger-ui:
    path: /bot/api/v1/swagger-ui

