app:
  telegram-token: ${TELEGRAM_API_KEY}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  show-actuator: true
  swagger-ui:
    path: /bot/api/v1/swagger-ui
