app:
  telegram-token: ${TELEGRAM_API_KEY}
  scrapper-url:
    default-url: http://localhost:8080/scrapper/api/v1
  scrapper-retry-config:
    type: constant
    delay: 2s
    max-retries: 3
    retry-on-statuses:
      - SERVER_ERROR

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  show-actuator: true
  swagger-ui:
    path: /bot/api/v1/swagger-ui
